export const formateurs = [
  {
    id: 'F1',
    nom: 'Bennour',
    prenom: 'Ahmed',
    mail: 'ahmed.bennour@ieee.tn',
    cin: '12345678',
    pays: 'Tunisie',
    cv: 'ahmed_bennour_cv.pdf',
    dateNaissance: '1985-03-15',
    lieuTravail: 'Polytech Tunis',
    image: 'assets/123.avif'
  },
  {
    id: 'F2',
    nom: 'Khaled',
    prenom: 'Leila',
    mail: 'leila.khaled@ieee.tn',
    cin: '87654321',
    pays: 'Tunisie',
    cv: 'leila_khaled_cv.pdf',
    dateNaissance: '1980-07-22',
    lieuTravail: 'ENSI',
    image: 'assets/123.avif'
  },
  {
    id: 'F3',
    nom: 'Trabelsi',
    prenom: 'Mohamed',
    mail: 'mohamed.trabelsi@ieee.tn',
    cin: '23456789',
    pays: 'Tunisie',
    cv: 'mohamed_trabelsi_cv.pdf',
    dateNaissance: '1978-11-30',
    lieuTravail: 'INSAT',
    image: 'assets/123.avif'
  },
  {
    id: 'F4',
    nom: 'Zaidi',
    prenom: 'Rayan',
    mail: 'rayan.zaidi@ieee.tn',
    cin: '34567890',
    pays: 'Tunisie',
    cv: 'rayan_zaidi_cv.pdf',
    dateNaissance: '1990-05-18',
    lieuTravail: 'ISET Com',
    image: 'assets/123.avif'
  },
  {
    id: 'F5',
    nom: 'Hamza',
    prenom: 'Karim',
    mail: 'karim.hamza@ieee.tn',
    cin: '45678901',
    pays: 'Tunisie',
    cv: 'karim_hamza_cv.pdf',
    dateNaissance: '1982-09-12',
    lieuTravail: 'ENIT',
    image: 'assets/123.avif'
  },
  {
    id: 'F6',
    nom: 'Meddeb',
    prenom: 'Sonia',
    mail: 'sonia.meddeb@ieee.tn',
    cin: '56789012',
    pays: 'Tunisie',
    cv: 'sonia_meddeb_cv.pdf',
    dateNaissance: '1987-01-25',
    lieuTravail: 'ESPRIT',
    image: 'assets/123.avif'
  },
  {
    id: 'F7',
    nom: 'Belhadj',
    prenom: 'Tariq',
    mail: 'tariq.belhadj@ieee.tn',
    cin: '67890123',
    pays: 'Tunisie',
    cv: 'tariq_belhadj_cv.pdf',
    dateNaissance: '1983-04-08',
    lieuTravail: 'Sup\'Com',
    image: 'assets/123.avif'
  },
  {
    id: 'F8',
    nom: 'Saïdi',
    prenom: 'Nabil',
    mail: 'nabil.saidi@ieee.tn',
    cin: '78901234',
    pays: 'Tunisie',
    cv: 'nabil_saidi_cv.pdf',
    dateNaissance: '1979-12-17',
    lieuTravail: 'ISAMM',
    image: 'assets/123.avif'
  },
  {
    id: 'F9',
    nom: 'Ghorbel',
    prenom: 'Hatem',
    mail: 'hatem.ghorbel@ieee.tn',
    cin: '89012345',
    pays: 'Tunisie',
    cv: 'hatem_ghorbel_cv.pdf',
    dateNaissance: '1975-06-14',
    lieuTravail: 'ISG Tunis',
    image: 'assets/123.avif'
  },
  {
    id: 'F10',
    nom: 'Ben Ali',
    prenom: 'Fatima Zahra',
    mail: 'fatima.benali@ieee.tn',
    cin: '90123456',
    pays: 'Tunisie',
    cv: 'fatima_benali_cv.pdf',
    dateNaissance: '1988-02-28',
    lieuTravail: 'FST',
    image: 'assets/123.avif'
  },
  {
    id: 'F11',
    nom: 'Mekki',
    prenom: 'Yasmine',
    mail: 'yasmine.mekki@ieee.tn',
    cin: '01234567',
    pays: 'Tunisie',
    cv: 'yasmine_mekki_cv.pdf',
    dateNaissance: '1992-08-05',
    lieuTravail: 'ISD',
    image: 'assets/123.avif'
  },
  {
    id: 'F12',
    nom: 'Ben Romdhane',
    prenom: 'Khaled',
    mail: 'khaled.benromdhane@ieee.tn',
    cin: '11223344',
    pays: 'Tunisie',
    cv: 'khaled_benromdhane_cv.pdf',
    dateNaissance: '1976-10-19',
    lieuTravail: 'ENSI',
    image: 'assets/123.avif'
  },
  {
    id: 'F13',
    nom: 'Ben Ali',
    prenom: 'Sami',
    mail: 'sami.benali@ieee.tn',
    cin: '22334455',
    pays: 'Tunisie',
    cv: 'sami_benali_cv.pdf',
    dateNaissance: '1984-03-22',
    lieuTravail: 'IEEE Tunis',
    image: 'assets/123.avif'
  },
  {
    id: 'F14',
    nom: 'Mansouri',
    prenom: 'Nadia',
    mail: 'nadia.mansouri@ieee.tn',
    cin: '33445566',
    pays: 'Tunisie',
    cv: 'nadia_mansouri_cv.pdf',
    dateNaissance: '1981-07-11',
    lieuTravail: 'INSAT',
    image: 'assets/123.avif'
  },
  {
    id: 'F15',
    nom: 'Ben Salem',
    prenom: 'Amira',
    mail: 'amira.bensalem@ieee.tn',
    cin: '44556677',
    pays: 'Tunisie',
    cv: 'amira_bensalem_cv.pdf',
    dateNaissance: '1986-12-03',
    lieuTravail: 'ENIT',
    image: 'assets/123.avif'
  },
  {
    id: 'F16',
    nom: 'Chérif',
    prenom: 'Houssem',
    mail: 'houssem.cherif@ieee.tn',
    cin: '55667788',
    pays: 'Tunisie',
    cv: 'houssem_cherif_cv.pdf',
    dateNaissance: '1989-09-15',
    lieuTravail: 'Sup\'Com',
    image: 'assets/123.avif'
  },
  {
    id: 'F17',
    nom: 'Jendoubi',
    prenom: 'Wissem',
    mail: 'wissem.jendoubi@ieee.tn',
    cin: '66778899',
    pays: 'Tunisie',
    cv: 'wissem_jendoubi_cv.pdf',
    dateNaissance: '1991-04-27',
    lieuTravail: 'ISG Tunis',
    image: 'assets/123.avif'
  },
  {
    id: 'F18',
    nom: 'Riahi',
    prenom: 'Ali',
    mail: 'ali.riahi@ieee.tn',
    cin: '77889900',
    pays: 'Tunisie',
    cv: 'ali_riahi_cv.pdf',
    dateNaissance: '1977-11-08',
    lieuTravail: 'FST',
    image: 'assets/123.avif'
  }
];